services:
  web:
    build: .
    image: psusphere:latest
    working_dir: /app/projectsite
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
